version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restoring Packages
          command:
            dotnet restore
      - run:
          name: Cleaning Application
          command:
            dotnet clean
      - run:
          name: Building Application
          command:
            dotnet build
      # - run:
      #     name: Starting Application
      #     command: 
      #       dotnet run
      # - run:
      #     name: Stop Building
      #     command:
      #       circleci-agent step halt
workflows:
  version: 2
  develop:
    jobs:
      - build:
          filters:
            branches:
              only: master       # only run builds when a push on master branch happens